FROM rust:1.84.0 as builder
WORKDIR /app
COPY . /app
RUN cargo build --release

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/target/release/hello-world-distroless /
CMD ["./hello-world-distroless"]
